### ISSUE TITLE
Reddit stoped working

### ISSUE THREAD

**Issue by isc30** [tgallant/embedd#118]
Hi, from today something changes in reddit api, and everything stopped working.
Embedd is currently calling:

https://www.reddit.com/search.json?q=url:http://blog.codeisc.com/2017/12/26/cpp-comma-operator-introduction.html 

and it doesn't find anything. BUT if you remove the `url:`, it works:

https://www.reddit.com/search.json?q=http://blog.codeisc.com/2017/12/26/cpp-comma-operator-introduction.html

not sure if this is a reddit bug or embeddd

**Comment by tgallant** [comment]
Thanks @isc30 I will dig into this

**Comment by isc30** [comment]
This fix may introduce error cases, when someone posted a link to your url it will parse it. There is some extra heuristic needed to pick 1 of the results (if the title is the url?)
